language: go
go:
  - 1.5
services:
  - redis-server
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get github.com/coreos/etcd
before_script:
  - $HOME/gopath/bin/etcd &
  - echo 'CREATE DATABASE PandoCloud' | mysql -uroot
script:
  - cd $HOME/gopath/src/github.com/PandoCloud/pando-cloud/
  - bash ./runtest.bash
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
