language: go
go:
  - 1.5
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/coreos/etcd
  - go install github.com/coreos/etcd
before_script:
  - $HOME/gopath/bin/etcd &
script:
  - go test -v -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
